name: NereidClientEnv

channels:
  - conda-forge

dependencies:
  - python=3.12
  - numpy=2.4
  - matplotlib=3.9
  - mplhep
  - pip

  - pip:
    - grpcio>=1.62.0
    - grpcio-tools>=1.62.0
    - protobuf>=4.25.0
    - PyYAML>=6.0.0
    - tritonclient[all]
