use std::fmt::Write as _;
use std::path::Path;

fn main() -> Result<(), Box<dyn std::error::Error>> {
    let protoc = protoc_bin_vendored::protoc_bin_path()?;
    let mut prost_config = prost_build::Config::new();
    prost_config.protoc_executable(protoc);

    // Both protos declare `package inference;`, so prost merges them into a
    // single generated module included via `tonic::include_proto!("inference")`.
    // grpc_service.proto is the Triton-compatible KServe v2 surface.
    tonic_prost_build::configure().compile_with_config(
        prost_config,
        &["proto/inference.proto", "proto/grpc_service.proto"],
        &["proto"],
    )?;

    generate_backend_modules()?;

    Ok(())
}

/// Discover every backend by globbing the subdirectories of `src/backends/` and
/// emit one `mod` declaration per `<name>/mod.rs`. `src/backends/mod.rs`
/// `include!`s the result, so adding a backend is just dropping a new
/// self-contained folder there — no registration, enum arm, or module list to
/// edit anywhere. Because each backend is its own directory, it can be vendored
/// as a git submodule; a folder without a `mod.rs` (e.g. an uninitialized
/// submodule) is skipped. Each backend compiles as `crate::backends::<dir-name>`
/// via an absolute `#[path]`.
///
/// Which discovered backends are actually built is a build-time *selection*
/// ([`backend_selection`]), not a Cargo feature list: Cargo features can only
/// name backends the manifest already knows about, which an out-of-tree or
/// submodule backend by definition doesn't. The selection is by name pattern, so
/// it can include or exclude a backend this repo has never heard of.
fn generate_backend_modules() -> Result<(), Box<dyn std::error::Error>> {
    let manifest_dir = std::env::var("CARGO_MANIFEST_DIR")?;
    let backends_dir = Path::new(&manifest_dir).join("src/backends");
    // Re-run when a backend folder is added or removed (the directory mtime moves).
    println!("cargo:rerun-if-changed={}", backends_dir.display());

    let selection = backend_selection(Path::new(&manifest_dir))?;

    let mut names = Vec::new();
    let mut skipped = Vec::new();
    for entry in std::fs::read_dir(&backends_dir)? {
        let path = entry?.path();
        // A backend is a subdirectory containing a `mod.rs`. Skip stray files and
        // empty folders (an uninitialized git submodule has no `mod.rs` yet).
        if !path.join("mod.rs").is_file() {
            continue;
        }
        let name = path
            .file_name()
            .and_then(|s| s.to_str())
            .ok_or("backend folder has no valid name")?
            .to_string();
        if selection.selects(&name) {
            names.push(name);
        } else {
            skipped.push(name);
        }
    }
    // Stable order → deterministic, reproducible output.
    names.sort();
    skipped.sort();
    // Never drop a backend silently: say what the selection excluded.
    if !skipped.is_empty() {
        println!(
            "cargo:warning=backend selection ({}) excluded: {}",
            selection.origin,
            skipped.join(", ")
        );
    }

    let mut out = String::from("// @generated by build.rs — one `mod` per folder in backends/.\n");
    for name in &names {
        let module = backends_dir.join(name).join("mod.rs");
        // Absolute path keeps resolution independent of where this is `include!`d.
        writeln!(out, "#[path = {:?}]\nmod {name};", module.display())?;
        // Editing a backend also re-runs this script (and recompiles).
        println!("cargo:rerun-if-changed={}", module.display());
    }

    let out_dir = std::env::var("OUT_DIR")?;
    std::fs::write(Path::new(&out_dir).join("backend_modules.rs"), out)?;
    Ok(())
}

/// Which discovered backend folders to compile in, as name patterns.
struct BackendSelection {
    /// Patterns a backend must match at least one of. Empty = take everything.
    include: Vec<String>,
    /// Patterns that exclude a backend outright; these beat `include`.
    exclude: Vec<String>,
    /// Where the patterns came from, for the excluded-backends warning.
    origin: String,
}

impl BackendSelection {
    fn selects(&self, name: &str) -> bool {
        if self.exclude.iter().any(|p| glob_matches(p, name)) {
            return false;
        }
        self.include.is_empty() || self.include.iter().any(|p| glob_matches(p, name))
    }
}

/// Read the backend selection from `$NEREID_BACKENDS`, else from a `backends.conf`
/// beside `Cargo.toml`, else select everything discovered.
///
/// Both sources use the same syntax: a list of name patterns separated by commas
/// or newlines, `*` matching any run of characters, a leading `!` excluding. In
/// the file, `#` starts a comment. So `onnx,tensorflow` builds exactly those two,
/// `!torch` builds everything but torch, and `!experimental-*` drops a family of
/// vendored backends. An empty value selects everything, same as unset.
fn backend_selection(manifest_dir: &Path) -> Result<BackendSelection, Box<dyn std::error::Error>> {
    println!("cargo:rerun-if-env-changed=NEREID_BACKENDS");
    let conf = manifest_dir.join("backends.conf");
    println!("cargo:rerun-if-changed={}", conf.display());

    let (spec, origin) = match std::env::var("NEREID_BACKENDS") {
        Ok(spec) if !spec.trim().is_empty() => (spec, "NEREID_BACKENDS".to_string()),
        _ if conf.is_file() => (std::fs::read_to_string(&conf)?, "backends.conf".to_string()),
        _ => (String::new(), String::new()),
    };

    let mut selection = BackendSelection {
        include: Vec::new(),
        exclude: Vec::new(),
        origin,
    };
    for pattern in spec
        .lines()
        .map(|line| line.split('#').next().unwrap_or(""))
        .flat_map(|line| line.split(','))
        .map(str::trim)
        .filter(|p| !p.is_empty())
    {
        match pattern.strip_prefix('!') {
            Some(negated) if !negated.is_empty() => selection.exclude.push(negated.to_string()),
            Some(_) => return Err("backend selection has a bare '!' with no pattern".into()),
            None => selection.include.push(pattern.to_string()),
        }
    }
    Ok(selection)
}

/// Match `name` against a pattern where `*` stands for any run of characters.
/// Anchored at both ends, so `onnx` matches only `onnx`, not `onnx-legacy`,
/// while `onnx*` matches both.
fn glob_matches(pattern: &str, name: &str) -> bool {
    let literals: Vec<&str> = pattern.split('*').collect();
    // No `*`: a plain name comparison.
    let [only] = literals[..] else {
        // The text before the first `*` anchors the start, the text after the
        // last one anchors the end, and the rest must occur in between, in order.
        let (first, last) = (literals[0], literals[literals.len() - 1]);
        let Some(mut rest) = name.strip_prefix(first) else {
            return false;
        };
        if rest.len() < last.len() || !rest.ends_with(last) {
            return false;
        }
        rest = &rest[..rest.len() - last.len()];
        for middle in &literals[1..literals.len() - 1] {
            match rest.find(middle) {
                Some(idx) => rest = &rest[idx + middle.len()..],
                None => return false,
            }
        }
        return true;
    };
    only == name
}
