use std::fmt::Write as _;
use std::path::Path;

fn main() -> Result<(), Box<dyn std::error::Error>> {
    let protoc = protoc_bin_vendored::protoc_bin_path()?;
    let mut prost_config = prost_build::Config::new();
    prost_config.protoc_executable(protoc);

    // Both protos declare `package inference;`, so prost merges them into a
    // single generated module included via `tonic::include_proto!("inference")`.
    // grpc_service.proto is the Triton-compatible KServe v2 surface.
    tonic_prost_build::configure().compile_with_config(
        prost_config,
        &["proto/inference.proto", "proto/grpc_service.proto"],
        &["proto"],
    )?;

    generate_backend_modules()?;

    Ok(())
}

/// Discover every backend by globbing the subdirectories of `src/backends/` and
/// emit one `mod` declaration per `<name>/mod.rs`. `src/backends/mod.rs`
/// `include!`s the result, so adding a backend is just dropping a new
/// self-contained folder there — no registration, enum arm, or module list to
/// edit anywhere. Because each backend is its own directory, it can be vendored
/// as a git submodule; a folder without a `mod.rs` (e.g. an uninitialized
/// submodule) is skipped. Each backend compiles as `crate::backends::<dir-name>`
/// via an absolute `#[path]`.
fn generate_backend_modules() -> Result<(), Box<dyn std::error::Error>> {
    let manifest_dir = std::env::var("CARGO_MANIFEST_DIR")?;
    let backends_dir = Path::new(&manifest_dir).join("src/backends");
    // Re-run when a backend folder is added or removed (the directory mtime moves).
    println!("cargo:rerun-if-changed={}", backends_dir.display());

    let mut names = Vec::new();
    for entry in std::fs::read_dir(&backends_dir)? {
        let path = entry?.path();
        // A backend is a subdirectory containing a `mod.rs`. Skip stray files and
        // empty folders (an uninitialized git submodule has no `mod.rs` yet).
        if !path.join("mod.rs").is_file() {
            continue;
        }
        let name = path
            .file_name()
            .and_then(|s| s.to_str())
            .ok_or("backend folder has no valid name")?
            .to_string();
        names.push(name);
    }
    // Stable order → deterministic, reproducible output.
    names.sort();

    let mut out = String::from("// @generated by build.rs — one `mod` per folder in backends/.\n");
    for name in &names {
        let module = backends_dir.join(name).join("mod.rs");
        // Absolute path keeps resolution independent of where this is `include!`d.
        writeln!(out, "#[path = {:?}]\nmod {name};", module.display())?;
        // Editing a backend also re-runs this script (and recompiles).
        println!("cargo:rerun-if-changed={}", module.display());
    }

    let out_dir = std::env::var("OUT_DIR")?;
    std::fs::write(Path::new(&out_dir).join("backend_modules.rs"), out)?;
    Ok(())
}
